-- Test inputs. Values not listed here are fixed in the query.
--   activeOnly = true
--   ageBand = "adult"
--   departmentId = 3
--   departmentIds = [1 2 3]
--   emailDomains = [%@example.com %@corp.example]
--   limit = 100
--   q = "%ali%"
--   sortKey = "recent"
--   status = "active"
--   tags = [vip beta]
--   withDepartment = true
-- Generated by `go test ./... -update`; edit sql/**/*.sql, not this file.

-- User search endpoint.
--
-- One template serves both the catalog search and the "my department" view; the only difference
-- is which optional predicates are supplied. Every optional predicate is a conjunction hung off
-- the `where 1 = 1` anchor, so an unsupplied filter drops out of the SQL entirely instead of
-- turning the query into a disjunction. Keeping it conjunctive is what lets one template back
-- both callers without the planner losing the index on the driving filter.
--
-- Anchoring, fragment by fragment:
--   - WHERE: `1 = 1` anchor; each optional predicate leads with `and`.
--   - ORDER BY: `u.id` is the stable trailing key; optional sort keys are prepended with a
--     trailing comma inside their own `/*%if*/`. A sort key is whitelisted SQL, never a bound
--     value — a column name cannot be parameterized.
--   - the keyword loop leads each iteration with `and`, off the same `1 = 1` anchor.
--   - `withDepartment` gates the projected column and its join together, so the two never
--     disagree.
select
    u.id,
    u.name,
    u.email
    , d.name as department
from users u
join departments d on d.id = u.department_id
where 1 = 1
-- Row-visibility scope shared by every users query: an optional active-only filter (its own
-- reusable fragment) and an optional single-department filter. Both are conjunctions, so the
-- scope contributes nothing when neither is requested.
and u.status = 'active'

and u.department_id = 3

 and u.age >= 18
and u.name like '%ali%'
and u.department_id in (1, 2, 3)
and exists (select 1 from user_tags ut where ut.user_id = u.id and ut.tag in ('vip', 'beta'))
 and u.email like '%@example.com' and u.email like '%@corp.example'
order by u.id desc, u.id
limit 100
