-- Test inputs. Values not listed here are fixed in the query.
--   (none)
-- Generated by `go test ./... -update`; edit sql/**/*.sql, not this file.

-- User search endpoint.
--
-- One template serves both the catalog search and the "my department" view; the only difference
-- is which optional predicates are supplied. Every optional predicate is a conjunction hung off
-- the `where 1 = 1` anchor, so an unsupplied filter drops out of the SQL entirely instead of
-- turning the query into a disjunction. Keeping it conjunctive is what lets one template back
-- both callers without the planner losing the index on the driving filter.
--
-- Anchoring, fragment by fragment:
--   - WHERE: `1 = 1` anchor; each optional predicate leads with `and`.
--   - ORDER BY: `u.id` is the stable trailing key; optional sort keys are prepended with a
--     trailing comma inside their own `/*%if*/`. A sort key is whitelisted SQL, never a bound
--     value — a column name cannot be parameterized.
--   - the keyword loop leads each iteration with `and`, off the same `1 = 1` anchor.
--   - `withDepartment` gates the projected column and its join together, so the two never
--     disagree.
select
    u.id,
    u.name,
    u.email
    
from users u

where 1 = 1
-- Row-visibility scope shared by every users query: an optional active-only filter (its own
-- reusable fragment) and an optional single-department filter. Both are conjunctions, so the
-- scope contributes nothing when neither is requested.




 and u.age >= 0




order by u.id
limit 50
