package query

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/samber/lo"

	"github.com/mpyw/bisql"
	"github.com/mpyw/bisql/dialect"
)

var update = flag.Bool("update", false, "update the .snapshot.sql golden files")

// TestSnapshots pins each SQL template independently of the database. For each query it:
//
//   - pins testdata/snapshots/<name>.expanded.sql (every @include resolved); and
//   - builds the template for a set of parameter cases, asserting Args and pinning the
//     values-embedded rendering in testdata/snapshots/<name>.<case>.embedded.sql.
//
// Regenerate the snapshots with `go test ./... -update`.
func TestSnapshots(t *testing.T) {
	p := bisql.NewParser(bisql.WithDialect(dialect.SQLite))

	type snapCase struct {
		name   string
		params map[string]any
		args   []any
	}
	type queryEntry struct {
		root  string // path under sql/
		cases []snapCase
	}
	queries := []queryEntry{
		{
			root: "users/search.sql",
			cases: []snapCase{
				{
					name: "full",
					params: map[string]any{
						"withDepartment": true,
						"activeOnly":     true,
						"status":         "active",
						"departmentId":   3,
						"ageBand":        "adult",
						"q":              "%ali%",
						"departmentIds":  []any{1, 2, 3},
						"tags":           []any{"vip", "beta"},
						"emailDomains":   []any{"%@example.com", "%@corp.example"},
						"sortKey":        "recent",
						"limit":          100,
					},
					args: []any{"active", 3, "%ali%", 1, 2, 3, "vip", "beta", "%@example.com", "%@corp.example"},
				},
				{name: "minimal", params: map[string]any{}, args: nil},
			},
		},
		{
			root: "audit_logs/activity-report.sql",
			cases: []snapCase{
				{
					name:   "windowed",
					params: map[string]any{"since": "2025-01-01", "until": "2025-12-31", "actions": []any{"login", "logout"}},
					args:   []any{"2025-01-01", "2025-12-31", "login", "logout"},
				},
				{name: "all_time", params: map[string]any{}, args: nil},
			},
		},
		{
			root: "audit_logs/bulk-insert.sql",
			cases: []snapCase{
				{
					name: "two_rows",
					params: map[string]any{"events": []any{
						map[string]any{"userId": 1, "action": "login"},
						map[string]any{"userId": 2, "action": "logout"},
					}},
					args: []any{1, "login", 2, "logout"},
				},
				{name: "empty", params: map[string]any{"events": []any{}}, args: nil},
			},
		},
		{
			root: "audit_logs/find-by-keys.sql",
			cases: []snapCase{
				{
					name: "two_keys",
					params: map[string]any{"keys": []any{
						map[string]any{"userId": 1, "action": "login"},
						map[string]any{"userId": 2, "action": "logout"},
					}},
					args: []any{1, "login", 2, "logout"},
				},
				{name: "empty", params: map[string]any{"keys": []any{}}, args: nil},
			},
		},
	}

	lo.ForEach(queries, func(q queryEntry, _ int) {
		t.Run(q.root, func(t *testing.T) {
			id := strings.TrimSuffix(q.root, ".sql")

			expanded, err := bisql.ExpandFile(templates, q.root)
			if err != nil {
				t.Fatalf("expand: %v", err)
			}
			checkGolden(t, filepath.Join("testdata", "snapshots", id+".expanded.sql"), expandedSnapshot(id, expanded))

			tmpl, err := p.ParseFile(templates, q.root)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			lo.ForEach(q.cases, func(c snapCase, _ int) {
				t.Run(c.name, func(t *testing.T) {
					stmt, err := tmpl.Build(c.params)
					if err != nil {
						t.Fatalf("build: %v", err)
					}
					if !reflect.DeepEqual(stmt.Args, c.args) {
						t.Errorf("Args\n got: %#v\nwant: %#v", stmt.Args, c.args)
					}
					checkGolden(t, filepath.Join("testdata", "snapshots", id+"."+c.name+".embedded.sql"), bindSnapshot(c.params, stmt.SQLWithArgs()))
				})
			})
		})
	})
}

// expandedSnapshot wraps an @include-expanded template in the generated-file banner written to
// testdata/snapshots/<id>.expanded.sql.
func expandedSnapshot(id, expanded string) string {
	return fmt.Sprintf("-- Code generated from sql/%s.sql; DO NOT EDIT. Regenerate with `go test ./... -update`.\n", id) +
		"-- The two-way template with every @include expanded.\n\n" +
		expanded
}

// bindSnapshot is the reviewable, values-embedded rendering for one parameter case, prefixed
// with the inputs that produced it so a reviewer can read the query without cross-referencing.
func bindSnapshot(params map[string]any, embedded string) string {
	keys := lo.Keys(params)
	sort.Strings(keys)
	lines := lo.Map(keys, func(k string, _ int) string {
		return fmt.Sprintf("--   %s = %s\n", k, formatInput(params[k]))
	})
	return "-- Test inputs. Values not listed here are fixed in the query.\n" +
		lo.Ternary(len(keys) == 0, "--   (none)\n", strings.Join(lines, "")) +
		"-- Generated by `go test ./... -update`; edit sql/**/*.sql, not this file.\n\n" +
		lo.Ternary(strings.HasSuffix(embedded, "\n"), embedded, embedded+"\n")
}

func formatInput(v any) string {
	switch x := v.(type) {
	case nil:
		return "null"
	case string:
		return strconv.Quote(x)
	default:
		return fmt.Sprintf("%v", x)
	}
}

func checkGolden(t *testing.T, path, got string) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read snapshot %s: %v (regenerate with: go test ./... -update)", path, err)
	}
	if got != string(want) {
		t.Errorf("%s mismatch\n--- got ---\n%s\n--- want ---\n%s", path, got, want)
	}
}
