-- Test inputs. Values not listed here are fixed in the query.
--   actions = [login logout]
--   since = "2025-01-01"
--   until = "2025-12-31"
-- Generated by `go test ./... -update`; edit sql/**/*.sql, not this file.

-- Per-department activity report over the audit log.
--
-- The reporting window is assembled from reusable fragments (`window` pulls in `since`), so the
-- lower and upper bounds are defined once and shared across every report. Each bound is a
-- conjunction off the `where 1 = 1` anchor and drops out when its parameter is absent, so
-- "all time" and "a bounded window" are the same template with different inputs.
select
    d.name as department,
    count(*) as events
from audit_logs a
join users u on u.id = a.user_id
join departments d on d.id = u.department_id
where 1 = 1
and a.created_at >= '2025-01-01'

and a.created_at < '2025-12-31'

and a.action in ('login', 'logout')
group by d.name
order by events desc, d.name
